---
title: "development enviroments"
author: "Javier Gracia-Tabuenca"
date: "2/7/2022"
output: html_document
---


## Development 
Before any of the following steps you need a github token to access the code in the private repositories. Set the environmental variable `GITHUB_PAT` with a token generated in [github.com/settings/tokens](https://github.com/settings/tokens). Token should include following permissions: "gist, repo, user, workflow". Following code helps you to do that from R: 

```{r, eval=FALSE}
# generate tocken 
usethis::create_github_token()

# copy and paste in 
Sys.setenv(GITHUB_PAT="<paste_token>")
```

### Development in laptop 
For development you can clone this repository and use `renv::` to install all the dependent packages. 

`renv::` automatically installs its self at the opening of the project. Then, run `renv::restore()` to install the dependent packages. 

### Development in SandBox 
SandBox has not connection to the internet. 
However, dependencies cant be build in a temporal IVM with connection to the internet, zipped, and copy into SandBox IVM. 
(note: the temporal IVM should have the same operating system and R version)

Follow `renv::` instruction for a such situation: 

> Clone the package on a computer with internet connection. 
> Specify the folder where your packages are stored by setting the RENV_PATHS_CACHE location (run `Sys.setenv("RENV_PATHS_CACHE"=paste0(getwd(),"/renv/cache"))`).
> Then run `renv::restore()` in the console. 
> Manually move the study package to the environment without internet (this now includes all required R packages), activate the current project with `renv::activate()` and again run `Sys.setenv("RENV_PATHS_CACHE"=paste0(getwd(),"/renv/cache"))` followed by `renv::restore()` in the console.


### Configure development enviroment
Configuration for your development environment can be set in `inst/golem-config.yml`. 
And selected on run time seting the envar `GOLEM_CONFIG_ACTIVE` (see: [golem-config](https://engineering-shiny.org/golem.html?q=GOLEM_CONFIG_ACTIVE#golem-config))

Currently this file includes three environments: 

- `no_connection`: To work with no connection to an Atlas instance. 
- `atlas-development`: To work with Atlas installed in an ivm in the atlas-development project in GCP. 
This environment needs the following additional yalm variables to configure [FinnGen/CDMTools](https://github.com/FinnGen/CDMTools).   - `CDMTOOLS_dbms` = "bigquery-dbi"
  - `GCP_PROJECT_ID` = "atlas-development-270609" 
  - `GCP_BILLING_PROJECT_ID` = "atlas-development-270609"
  - `CDMTOOLS_webapi_url` = "http://localhost/WebAPI"
  - `CDMTOOLS_CDM_source_key_test` = "dummy_df6v2_1k_13_FinnGen_omop_bq"
  - `GCP_SERVICE_KEY`: path to the GCP key to access the BQ in atlas-development
  
- `SandBox`: To work in SandBox.
SandBox must have set the following environmental variable `BUCKET_SandBox_IVM` with bigquery's billing project name ending in "_ivm" (eg. "fg-production-SandBox-4_ivm"). 
This environment  also needs the following yalm variables: 
  - `CDMTOOLS_dbms` = "bigquery-dbi"
  - `GCP_PROJECT_ID` = "FinnGen-production-library"
  - `CDMTOOLS_webapi_url` = "https://ohdsi-webapi.app.FinnGen.fi/WebAPI"
  - `CDMTOOLS_CDM_source_key_test` = "FinnGen_CDM_R7"


