default:
  golem_name: CohortOperationsShinyApp
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev_laptop_javier:
  enviroment: atlas-development
  app_prod: no
  CDMTOOLS_dbms: bigquery-dbi
  GCP_PROJECT_ID: atlas-development-270609
  GCP_BILLING_PROJECT_ID: atlas-development-270609
  CDMTOOLS_webapi_url: http://localhost/WebAPI
  GCP_SERVICE_KEY: C:\Users\javier\.ssh\gq\computerenginedfault.json
  CDMTOOLS_CDM_source_key_test: dummy_df6v2_1k_13_finngen_omop_bq
dev_no_connection:
  golem_name: CohortOperationsShinyApp
  golem_version: 0.0.0.9000
  enviroment: no-connection
  app_prod: no
dev:
  golem_wd: !expr here::here()
